export const HELP_TEXT = [
  "commands:",
  "  /new <name>    create a new project",
  "  /open <path>   open an existing project",
  "  /switch <id>   switch to a project by id",
  "  /workspace [name]  tag current project with workspace",
  "  /files         toggle file tree panel",
  "  /terminal      toggle terminal panel",
  "  /search        toggle search panel",
  "  /git           toggle git panel",
  "  /todos         toggle TODO panel",
  "  /snippets      toggle snippet library",
  "  /plugins       toggle plugin panel",
  "  /debug         toggle debug panel",
  "  /share [url]   start collab session",
  "  /join <url> <room>  join collab session",
  "  /refresh       refresh file tree",
  "  /commit [msg]  commit changes",
  "  /diff          show git diff",
  "  /status        show git status",
  "  /pr [desc]     create pull request",
  "  /log           show git log",
  "  /review        AI code review",
  "  /summary       summarize project",
  "  /tutorial      interactive tutorial",
  "  /help          show this help",
  "",
  "  !<cmd>         run a shell command",
  "  !!<query>      natural language -> command",
  "  anything else  talk to the AI",
].join("\n");
